INSERT INTO subjects (name, semester, hours_week) VALUES
('Física', 1, 4),
('Fundamentos de Matemáticas', 1, 5),
('Matemáticas Discretas', 1, 3),
('Metodología de la Programación', 1, 5),
('Programación Estructurada', 1, 5),
('Taller de Competencias Informacionales', 1, 4),
('Calculo Diferencial', 2, 4),
('Electricidad y Electrónica', 2, 4),
('Estructura de Datos', 2, 4),
('Programación Orientada a Objetos', 2, 4),
('Taller de Metodología de la Investigación', 2, 4),
('Algebra Lineal', 2, 4),
('Calculo Integral', 3, 4),
('Desarrollo Humano', 3, 4),
('Diseño de Bases de Datos', 3, 4),
('Métodos Númericos', 3, 4),
('Programación Avanzada', 3, 4),
('Sistemas Digitales', 3, 4),
('Taller de Desarrollo 1', 3, 4),
('Administración de Bases de Datos', 4, 4),
('Arquitectura de Computadoras', 4, 4),
('Ecuaciones Diferenciales', 4, 4),
('Estudio de las OrganizacionesS', 4, 4),
('Probabilidad y Estadística ', 4, 4),
('Programación Distribuida y en Paralelo', 4, 4),
('Taller de Desarrollo 2', 4, 4),
('Calidad en los procesos de Desarrollo de Software', 5, 4),
('Fundamentos de Redes', 5, 4),
('Investigación de Operaciones', 5, 4),
('Práctica Profesional 1', 5, 4),
('Taller de Desarrollo 3', 5, 4),
('Teoría Matemática de la Computación', 5, 4),
('Tópicos Avanzados de Bases de Datos', 5, 4),
('Traductores de Bajo Nivel', 5, 4),
('Compiladores', 6, 4),
('Contabilidad y Finanzas', 6, 4),
('Economía', 6, 4),
('Interfaces Humano Computadora', 6, 4),
('Modelos y Metodologías de desarrollo de Sotware', 6, 4),
('Protocolos de Enrutamiento', 6, 4),
('Taller de Desarrollo 4', 6, 4),
('Conmutadores y Redes Inalámbricas', 7, 4),
('Desarrollo de Aplicaciones Web y Móviles', 7, 4),
('Inteligencia Artificial', 7, 4),
('Opt. 1 - Seguridad en Cómputo', 7, 4),
('Opt. 2 - Análisis de Vulnerabilidades', 7, 4),
('Práctica Profesional 2', 7, 4),
('Sistemas Operativos', 7, 4),
('Administración de Sistemas Operativos', 8, 4),
('Cómputo Distribuido', 8, 4),
('Graficación', 8, 4),
('Opt. 3 - Respuesta a Incidentes de Seguridad', 8, 4),
('Opt. 4 - Cómputo Forense', 8, 4),
('Opt. 5 - Startup Tecnológicas', 8, 4),
('Taller de investigación en las ciencias computacionales', 8, 4),
('Residencia Profesional', 9, 4),
('Taller de Elaboración del Informe de Investigación', 9, 4);

INSERT INTO "groups" (name, semester) VALUES 
('1M', 1),
('1N', 1),
('1O', 1),
('2M', 2),
('2N', 2),
('3M', 3),
('3N', 3),
('3O', 3),
('4M', 4),
('5M', 5),
('5N', 5),
('5O', 5),
('6M', 6),
('7M', 7),
('7N', 7),
('7O', 7),
('8M', 8),
('9M', 9),
('9N', 9);

INSERT INTO teachers (name) VALUES 
('Genaro Hernández Martínez'),
('Victor Hugo Guzman de la Rosa'),
('Luis Alejandro Jonapa Chacon'),
('Justino López Aguilar'),
('Abel Centeno Galindo'),
('Octavio Morales Jiménez'),
('María de los Angeles Polanco Enciso'),
('Alejandro Conde Escaroz'),
('Enrique Gutiérrez Espinoza'),
('Kathiane Toledo Valdez'),
('Héctor Guerra Crespo'),
('Paola Lopez y Lopez'),
('Ricardo Vega Morales'),
('Rebeca Garzón Clemenete'),
('Jazmín Regina López Ocaña'),
('Gustavo Adolfo Andrade Gutiérrez'),
('Guadalupe Velazquez Ruiz'),
('Guiovanny Beney Zambrano Hernández'),
('Mario Toledo Pérez'),
('Yair Gonzalez Baldizon'),
('Luis Alejandro Trujillo Santos'),
('Mariana Paola Gonzalez Soria'),
('Daniel Gonzalez Scarpulli'),
('Victor Manuel Mendez Ovando'),
('Victor Rodulfo Sol Hernández'),
('Laura de Jesus Velasco Estrada'),
('Gilberto Wilfredo Lopez Cifuentes'),
('Rigoberto Pérez Ovando'),
('Jesus Carlos Sanchez Guzman'),
('Adan Nañez Coutiño'),
('Noe Toledo Castillejos'),}
('Juan Jose Tevera Mandujano'),
('Carlos Alberto García Ramos'),
('Luis Gutiérrez Alfaro'),
('José Alejandro Suárez Zenteno'),
('Héctor Roberto Noricumbo Castro'),
('Obeth Regalado Moreno'),
('Nuria González Zuñiga'),
('Hugo Adrian Pizaña Vidal'),
('Vicente Hernández Reyes'),
('Luis Manuel Sandoval Zuñiga'),
('Bernardo López Maldonado'),
('Rebeca Roman Julian');

INSERT INTO classrooms (name) VALUES 
('B1'),
('B2'),
('B3'),
('B4'),
('B5'),
('B6');
('A7');
('A8');
('C1');
('D1');
('LINEA');

INSERT INTO laboratories (name) VALUES 
('Laboratorio 1'),
('Laboratorio 2'),
('Laboratorio 3'),
('Laboratorio 4'),
('Laboratorio soporte 1'),
('Laboratorio soporte 2');